############# English navigation ##############

# main menu
[[main]]
name = "FJ2 Tech Inc"
url = "/"
weight = 1

[[main]]
weight = 2
name = "Services"
hasChildren = true

[[main]]
parent = "Services"
name = "Artificial Intelligence"
url = "services/ai/"
weight = 1

[[main]]
parent = "Services"
name = "Software Engineering"
url = "services/software/"
weight = 2

[[main]]
parent = "Services"
name = "Project Management"
url = "services/pm/"
weight = 3

[[main]]
weight = 3
name = "The Team"
url = "team/"

[[main]]
name = "About"
url = "about/"
weight = 4

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "elements/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
